trigger:
  batch: true
  branches:
    include:
      - PHP-7.4
      - PHP-8.0
      - master
  paths:
    exclude:
      - docs/*
      - NEWS
      - UPGRADING
      - UPGRADING.INTERNALS

schedules:
  - cron: "0 1 * * *"
    displayName: Nightly build
    branches:
      include:
        - PHP-7.4
        - PHP-8.0
        - master

jobs:
    - template: azure/i386/job.yml
      parameters:
        configurationName: I386_RELEASE_NTS
        configurationParameters: '--disable-debug --disable-zts'
        runTestsParameters: '-d opcache.jit_debug=0x1ff005 ext/opcache/tests/jit/fetch_dim_r_004.phpt'
