trigger:
  batch: true
  branches:
    include:
      - PHP-7.4
      - master
  paths:
    exclude:
      - docs/*
      - NEWS
      - UPGRADING
      - UPGRADING.INTERNALS

jobs:
  - template: azure/job.yml
    parameters:
      configurationName: DEBUG_ZTS_ASAN
      configurationParameters: >-
          --enable-debug --enable-zts
          CFLAGS='-fsanitize=address -DZEND_TRACK_ARENA_ALLOC'
          LDFLAGS='-fsanitize=address'
      runTestsParameters: --asan
      timeoutInMinutes: 240
  - template: azure/job.yml
    parameters:
      configurationName: DEBUG_ZTS_UBSAN
      configurationParameters: >-
          --enable-debug --enable-zts
          CFLAGS='-fsanitize=undefined'
          LDFLAGS='-fsanitize=undefined'
      timeoutInMinutes: 240
