trigger:
  batch: true
  branches:
    include:
      - PHP-7.4
      - PHP-8.0
      - master
  paths:
    exclude:
      - docs/*
      - NEWS
      - UPGRADING
      - UPGRADING.INTERNALS
      - README.md
      - CONTRIBUTING.md
      - CODING_STANDARDS.md

schedules:
  - cron: "0 1 * * *"
    displayName: Nightly build
    branches:
      include:
        - PHP-7.4
        - PHP-8.0
        - master

jobs:
    - template: azure/job.yml
      parameters:
        configurationName: VARIATION_DEBUG_ZTS
        configurationParameters: >-
            --enable-debug --enable-zts
            CFLAGS="-DZEND_RC_DEBUG=1 -DPROFITABILITY_CHECKS=0"
