trigger:
  batch: true
  branches:
    include:
      - PHP-7.4
      - master
  paths:
    exclude:
      - docs/*
      - NEWS
      - UPGRADING
      - UPGRADING.INTERNALS

jobs:
  - template: azure/i386/job.yml
    parameters:
      configurationName: I386_DEBUG_ZTS
      configurationParameters: '--enable-debug --enable-maintainer-zts'
  - template: azure/i386/job.yml
    parameters:
      configurationName: I386_DEBUG_NTS
      configurationParameters: '--enable-debug --disable-maintainer-zts'
  - template: azure/i386/job.yml
    parameters:
      configurationName: I386_RELEASE_NTS
      configurationParameters: '--disable-debug --disable-maintainer-zts'
  - template: azure/i386/job.yml
    parameters:
      configurationName: I386_RELEASE_ZTS
      configurationParameters: '--disable-debug --enable-maintainer-zts'
