trigger:
  batch: true
  branches:
    include:
      - PHP-7.4
      - master
  paths:
    exclude:
      - docs/*
      - NEWS
      - UPGRADING
      - UPGRADING.INTERNALS

jobs:
  - template: azure/job.yml
    parameters:
      configurationName: RELEASE_ZTS
      configurationParameters: '--disable-debug --enable-zts'
  - template: azure/job.yml
    parameters:
      configurationName: RELEASE_NTS
      configurationParameters: '--disable-debug --disable-zts --with-mm'
