trigger:
  batch: true
  branches:
    include:
      - PHP-7.4
      - PHP-8.0
      - master
  paths:
    exclude:
      - docs/*
      - NEWS
      - UPGRADING
      - UPGRADING.INTERNALS

schedules:
  - cron: "0 1 * * *"
    displayName: Nightly build
    branches:
      include:
        - PHP-7.4
        - PHP-8.0
        - master

jobs:
    - template: azure/msan_job.yml
      parameters:
        configurationName: RELASSERT_ZTS_MSAN
        configurationParameters: '--enable-debug-assertions --enable-zts'
        runTestsParameters: --msan
        timeoutInMinutes: 90
