trigger:
  batch: true
  branches:
    include:
      - PHP-7.4
      - master

jobs:
  - template: azure/job.yml
    parameters:
      configurationName: DEBUG_ZTS_ASAN_UBSAN
      configurationParameters: >-
          --enable-debug --enable-zts
          CFLAGS='-fsanitize=undefined,address -DZEND_TRACK_ARENA_ALLOC'
          LDFLAGS='-fsanitize=undefined,address'
      runTestsParameters: --asan
      timeoutInMinutes: 150
