parameters:
  configurationName: ''
  configurationParameters: ''

jobs:
  - job: ${{ parameters.configurationName }}
    pool:
      vmImage: 'macOS-10.15'
    steps:
    - template: brew.yml
    - script: |
        export PATH="/usr/local/opt/bison/bin:$PATH"
        export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/local/opt/openssl@1.1/lib/pkgconfig"
        export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/local/opt/krb5/lib/pkgconfig"
        export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/local/opt/libffi/lib/pkgconfig"
        export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/local/opt/libxml2/lib/pkgconfig"
        export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/local/opt/libxslt/lib/pkgconfig"
        export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/local/opt/zlib/lib/pkgconfig"
        export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/local/opt/icu4c/lib/pkgconfig"
        ./buildconf --force
        ./configure ${{ parameters.configurationParameters }} \
            --enable-option-checking=fatal \
            --prefix=/usr/local \
            --enable-fpm \
            --with-pdo-mysql=mysqlnd \
            --with-mysqli=mysqlnd \
            --with-pgsql=/usr/local/opt/libpq \
            --with-pdo-pgsql=/usr/local/opt/libpq \
            --with-pdo-sqlite \
            --without-pear \
            --enable-gd \
            --with-jpeg \
            --with-webp \
            --with-freetype \
            --enable-exif \
            --with-zip \
            --with-zlib \
            --enable-soap \
            --enable-xmlreader \
            --with-xsl \
            --with-tidy=/usr/local/opt/tidyp \
            --with-libxml \
            --enable-sysvsem \
            --enable-sysvshm \
            --enable-shmop \
            --enable-pcntl \
            --with-readline=/usr/local/opt/readline \
            --enable-mbstring \
            --with-curl \
            --with-gettext=/usr/local/opt/gettext \
            --enable-sockets \
            --with-bz2=/usr/local/opt/bzip2 \
            --with-openssl \
            --with-gmp=/usr/local/opt/gmp \
            --with-iconv=/usr/local/opt/libiconv \
            --enable-bcmath \
            --enable-calendar \
            --enable-ftp \
            --with-pspell=/usr/local/opt/aspell \
            --with-kerberos \
            --enable-sysvmsg \
            --with-ffi \
            --enable-zend-test \
            --enable-intl \
            --with-mhash \
            --with-sodium \
            --enable-dba \
            --enable-werror \
            --with-config-file-path=/etc \
            --with-config-file-scan-dir=/etc/php.d \
            CFLAGS='-Werror=implicit-function-declaration'
      displayName: 'Configure Build'
    - script: |
        export PATH="/usr/local/opt/bison/bin:$PATH"
        cc -Imain/streams/ -I/Users/runner/work/1/s/main/streams/ -I/Users/runner/work/1/s/include -I/Users/runner/work/1/s/main -I/Users/runner/work/1/s -I/Users/runner/work/1/s/ext/date/lib -I/usr/local/Cellar/libxml2/2.9.10_2/include/libxml2 -I/usr/local/Cellar/krb5/1.19.1/include -I/usr/local/Cellar/openssl@1.1/1.1.1k/include -I/usr/local/Cellar/zlib/1.2.11/include -I/usr/local/opt/bzip2/include -I/usr/local/Cellar/libffi/3.3_3/include -I/usr/local/Cellar/libpng/1.6.37/include/libpng16 -I/usr/local/Cellar/webp/1.2.0/include -I/usr/local/Cellar/jpeg/9d/include -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/opt/gettext/include -I/usr/local/opt/gmp/include -I/usr/local/opt/libiconv/include -I/usr/local/Cellar/icu4c/68.2/include -I/usr/local/Cellar/oniguruma/6.9.6/include -I/Users/runner/work/1/s/ext/mbstring/libmbfl -I/Users/runner/work/1/s/ext/mbstring/libmbfl/mbfl -I/usr/local/opt/libpq/include -I/usr/local/opt/aspell/include/pspell -I/usr/local/opt/readline/include -I/usr/local/Cellar/libsodium/1.0.18_1/include -I/usr/local/opt/tidyp/include/tidyp -I/usr/local/Cellar/libxslt/1.1.34_2/include -I/usr/local/Cellar/libzip/1.7.3/include -I/Users/runner/work/1/s/TSRM -I/Users/runner/work/1/s/Zend -fno-common -Wall -Wextra -Wno-strict-aliasing -Wno-unused-parameter -Wno-sign-compare -g -fvisibility=hidden -O0 -DZEND_SIGNALS -Werror -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -c /Users/runner/work/1/s/main/streams/plain_wrapper.c -MMD -MF main/streams/plain_wrapper.dep -MT main/streams/plain_wrapper.lo -E
        make -j$(sysctl -n hw.logicalcpu)
      displayName: 'Make Build'
    - script: |
        sudo make install
      displayName: 'Install Build'
    - template: test.yml
      parameters:
        configurationName: ${{ parameters.configurationName }}
    - ${{ if eq(variables['Build.Reason'], 'Schedule') }}:
      - template: test.yml
        parameters:
          configurationName: ${{ parameters.configurationName }}
          runTestsName: 'OpCache'
          runTestsParameters: -d zend_extension=opcache.so -d opcache.enable_cli=1 -d opcache.protect_memory=1
    - ${{ if eq(variables['Build.Reason'], 'Schedule') }}:
      - template: test.yml
        parameters:
          configurationName: ${{ parameters.configurationName }}
          runTestsName: 'Function JIT'
          runTestsParameters: -d zend_extension=opcache.so -d opcache.enable_cli=1 -d opcache.protect_memory=1 -d opcache.jit_buffer_size=16M -d opcache.jit=1205
    - template: test.yml
      parameters:
        configurationName: ${{ parameters.configurationName }}
        runTestsName: 'Tracing JIT'
        runTestsParameters: -d zend_extension=opcache.so -d opcache.enable_cli=1 -d opcache.protect_memory=1 -d opcache.jit_buffer_size=16M
